### PR TITLE
Fix incorrect painting of global FX bypasses

### LINKED ISSUE #4892: Incorrect FX bypasses after slot expansion
Pics will be self-explanatory:

image

image

Seems to be UI only, DSP-wise it's fine.

### PR DESCRIPTION
**Pull request by mkruselj**
Closes #4892

Also fixes color of send 3/4 sliders in Dark skin.

### CODE REVIEW

File: src/gui/widgets/EffectChooser.h [hunk 1]
```diff
@@ -102,11 +102,13 @@ struct EffectChooser : public juce::Component, public WidgetBaseMixin<EffectChoo
...
             return true;
         case fxb_no_sends:
-            if ((fxslot == 4) || (fxslot == 5))
+            if ((fxslot == fxslot_send1) || (fxslot == fxslot_send2) || (fxslot == fxslot_send3) ||
+                (fxslot == fxslot_send4))
                 return true;
             break;
         case fxb_scene_fx_only:
-            if (fxslot > 3)
+            if ((fxslot >= fxslot_send1 && fxslot == fxslot_global2) ||
```
Comment (baconpaul) [inline src/gui/widgets/EffectChooser.h:110]: Did you really mean al == in the second?
This will only be true for fxslot == global2 or global 4
I think you mean >= fxslot_send1 && <= fxslot_global2

**Comment by baconpaul** [comment]
think it has a tiny bug?

File: src/gui/widgets/EffectChooser.h (hunk 1 above)
Comment (baconpaul) [reply src/gui/widgets/EffectChooser.h]: yeah you definitely meant <=. Pushed a fix to your branch and will merge. Good catch!

Comment (mkruselj) [reply src/gui/widgets/EffectChooser.h]: Yes that was an unfortunate typo, I did mean to cover the range so <= was definitely needed there 🙂
