### PR TITLE
Fixed the widget disappearing act

### LINKED ISSUE #2225: The disappearing widgets act
Click on play mode, osc FM routing, filter config, filter type, waveshaper type, scene/osc octave, FX bypass, etc, hold the click then RMB.

They go poof. 

image

### PR DESCRIPTION
**Pull request by mkruselj**
* closes #2225

### CODE REVIEW

File: src/common/gui/CHSwitch2.cpp [hunk 1]
```diff
@@ -46,7 +46,11 @@ void CHSwitch2::draw(CDrawContext* dc)
 
 CMouseEventResult CHSwitch2::onMouseDown(CPoint& where, const CButtonState& buttons)
 {
-   if (listener && buttons & (kAlt | kShift | kRButton | kControl | kApple))
+   mouseDowns++;
+   if (mouseDowns > 1)
+      return kMouseEventHandled;
+
+   if (listener && buttons & (kAlt | kShift | kRButton | kControl | kApple) && !(buttons & kLButton))
```
Comment (baconpaul) [inline src/common/gui/CHSwitch2.cpp:53]: We shouldn't add this change now we have the mouseDowns handler

File: src/common/gui/CHSwitch2.h [hunk 2]
```diff
@@ -33,6 +33,7 @@ class CHSwitch2 : public VSTGUI::CHorizontalSwitch, public Surge::UI::SkinConsum
    // This matches the paint offset
    virtual int getIValue() { return (int)(value * (float)(rows * columns - 1) + 0.5f); }
    
+   int mouseDowns;
```
Comment (baconpaul) [inline src/common/gui/CHSwitch2.h:36]: You need to initialize mouseDowns to 0 in the CHSwitch constructor (so around line 29 of this file do a mouseDowns = 0)
